# frontend/Dockerfile
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json package-lock*.json ./
RUN npm ci
# copy source
COPY . .
RUN npm run build

# Serve with node
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package.json package-lock*.json ./
RUN npm ci --only=production
COPY server.js ./
EXPOSE 80
CMD ["node", "server.js"]
